const STOCK_CATALOG = [
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "Information Technology" },
  { symbol: "INFY", name: "Infosys", sector: "Information Technology" },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking" },
  { symbol: "ICICIBANK", name: "ICICI Bank", sector: "Banking" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", sector: "Banking" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", sector: "Banking" },
  { symbol: "FEDERALBNK", name: "Federal Bank", sector: "Banking" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Banking" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Financial Services" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Financial Services" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", sector: "Financial Services" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Financial Services" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", sector: "Financial Services" },
  { symbol: "PFC", name: "Power Finance Corporation", sector: "Financial Services" },
  { symbol: "RECLTD", name: "REC Limited", sector: "Financial Services" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", sector: "Financial Services" },
  { symbol: "JIOFIN", name: "Jio Financial Services", sector: "Financial Services" },
  { symbol: "LICI", name: "Life Insurance Corporation", sector: "Financial Services" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "Information Technology" },
  { symbol: "WIPRO", name: "Wipro", sector: "Information Technology" },
  { symbol: "TECHM", name: "Tech Mahindra", sector: "Information Technology" },
  { symbol: "LTIM", name: "LTIMindtree", sector: "Information Technology" },
  { symbol: "PERSISTENT", name: "Persistent Systems", sector: "Information Technology" },
  { symbol: "COFORGE", name: "Coforge", sector: "Information Technology" },
  { symbol: "MPHASIS", name: "Mphasis", sector: "Information Technology" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "Information Technology" },
  { symbol: "OFSS", name: "Oracle Financial Services Software", sector: "Information Technology" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "IDEA", name: "Vodafone Idea", sector: "Telecom" },
  { symbol: "TATACOMM", name: "Tata Communications", sector: "Telecom" },
  { symbol: "INDUSTOWER", name: "Indus Towers", sector: "Telecom" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Utilities" },
  { symbol: "NTPC", name: "NTPC", sector: "Utilities" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Utilities" },
  { symbol: "ADANIPOWER", name: "Adani Power", sector: "Utilities" },
  { symbol: "TATAPOWER", name: "Tata Power", sector: "Utilities" },
  { symbol: "TORNTPOWER", name: "Torrent Power", sector: "Utilities" },
  { symbol: "NHPC", name: "NHPC", sector: "Utilities" },
  { symbol: "JSWENERGY", name: "JSW Energy", sector: "Utilities" },
  { symbol: "SJVN", name: "SJVN", sector: "Utilities" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum", sector: "Energy" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum", sector: "Energy" },
  { symbol: "GAIL", name: "GAIL India", sector: "Energy" },
  { symbol: "OIL", name: "Oil India", sector: "Energy" },
  { symbol: "PETRONET", name: "Petronet LNG", sector: "Energy" },
  { symbol: "IGL", name: "Indraprastha Gas", sector: "Energy" },
  { symbol: "MGL", name: "Mahanagar Gas", sector: "Energy" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", sector: "Consumer" },
  { symbol: "ITC", name: "ITC", sector: "Consumer" },
  { symbol: "NESTLEIND", name: "Nestle India", sector: "Consumer" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer" },
  { symbol: "BRITANNIA", name: "Britannia Industries", sector: "Consumer" },
  { symbol: "DABUR", name: "Dabur India", sector: "Consumer" },
  { symbol: "MARICO", name: "Marico", sector: "Consumer" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "Consumer" },
  { symbol: "COLPAL", name: "Colgate Palmolive India", sector: "Consumer" },
  { symbol: "UBL", name: "United Breweries", sector: "Consumer" },
  { symbol: "VBL", name: "Varun Beverages", sector: "Consumer" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Automobile" },
  { symbol: "MARUTI", name: "Maruti Suzuki", sector: "Automobile" },
  { symbol: "M&M", name: "Mahindra and Mahindra", sector: "Automobile" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Automobile" },
  { symbol: "EICHERMOT", name: "Eicher Motors", sector: "Automobile" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", sector: "Automobile" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", sector: "Automobile" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", sector: "Automobile" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Automobile" },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Automobile" },
  { symbol: "LT", name: "Larsen and Toubro", sector: "Infrastructure" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Infrastructure" },
  { symbol: "GRASIM", name: "Grasim Industries", sector: "Infrastructure" },
  { symbol: "SHREECEM", name: "Shree Cement", sector: "Infrastructure" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", sector: "Infrastructure" },
  { symbol: "ACC", name: "ACC", sector: "Infrastructure" },
  { symbol: "SIEMENS", name: "Siemens India", sector: "Infrastructure" },
  { symbol: "ABB", name: "ABB India", sector: "Infrastructure" },
  { symbol: "CUMMINSIND", name: "Cummins India", sector: "Infrastructure" },
  { symbol: "DLF", name: "DLF", sector: "Infrastructure" },
  { symbol: "LODHA", name: "Macrotech Developers", sector: "Infrastructure" },
  { symbol: "GODREJPROP", name: "Godrej Properties", sector: "Infrastructure" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Infrastructure" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Healthcare" },
  { symbol: "DRREDDY", name: "Dr Reddys Laboratories", sector: "Healthcare" },
  { symbol: "CIPLA", name: "Cipla", sector: "Healthcare" },
  { symbol: "DIVISLAB", name: "Divis Laboratories", sector: "Healthcare" },
  { symbol: "LUPIN", name: "Lupin", sector: "Healthcare" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", sector: "Healthcare" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", sector: "Healthcare" },
  { symbol: "ALKEM", name: "Alkem Laboratories", sector: "Healthcare" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", sector: "Healthcare" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", sector: "Healthcare" },
  { symbol: "MAXHEALTH", name: "Max Healthcare", sector: "Healthcare" },
  { symbol: "FORTIS", name: "Fortis Healthcare", sector: "Healthcare" },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals" },
  { symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals" },
  { symbol: "HINDALCO", name: "Hindalco Industries", sector: "Metals" },
  { symbol: "JINDALSTEL", name: "Jindal Steel and Power", sector: "Metals" },
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals" },
  { symbol: "NATIONALUM", name: "National Aluminium Company", sector: "Metals" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper", sector: "Metals" },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Industrials" },
  { symbol: "ADANIPORTS", name: "Adani Ports", sector: "Industrials" },
  { symbol: "ZOMATO", name: "Zomato", sector: "Internet" },
  { symbol: "SWIGGY", name: "Swiggy", sector: "Internet" },
  { symbol: "PAYTM", name: "One 97 Communications", sector: "Internet" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", sector: "Internet" },
  { symbol: "IRCTC", name: "Indian Railway Catering and Tourism", sector: "Internet" },
  { symbol: "NAUKRI", name: "Info Edge India", sector: "Internet" },
  { symbol: "DELHIVERY", name: "Delhivery", sector: "Logistics" },
  { symbol: "BLUEDART", name: "Blue Dart Express", sector: "Logistics" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics" },
  { symbol: "INDIGO", name: "InterGlobe Aviation", sector: "Transportation" },
  { symbol: "SPICEJET", name: "SpiceJet", sector: "Transportation" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation", sector: "Transportation" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", sector: "Transportation" },
  { symbol: "IRCON", name: "Ircon International", sector: "Transportation" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Mining" },
];